# -*- coding: utf-8 -*-
"""labels.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x_ozX03Ohkd6QMgCEsQ5cUVuSvJ3udpH
"""

CLASS_NAMES = ["emotion", "social", "physical", "pose_idle"]

